# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1282e47e7fcc22b4509e6be56faabd652c9fd43960e9b032deb97c8355fccbc495525301953d8b91f89e5a6a1de765fda5a6e319a8104e80802321101ea12583

test:
  secret_key_base: 6f0e7e4b667f79ac8cdc42715d1858a4c9b094aaa18ffed1daffe38e3555a66cac9f54bc869620de55d2e778fceec9693c5f6c6be62f5cf8a79bc4607fba335f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
